### ISSUE TITLE
Nested Named Entity Recognition Training Corpus

### ISSUE THREAD

**Issue by Amphagory** [applicaai/poleval-2018#3]
How did you train Flair to predict nested named entity recognition, in terms of how would the training corpus look like?

i.e. Alex Tam is going to Los Angele

an example of an IOB for this would be,

Alex B-PER
Tam I-PER
is O
going O
to O
Los B-LOC
Angeles I-LOC

What happens if we wanted label the two words Los Angeles with CITY, wonder how to label the training data?

**Comment by Borchmann** [comment]
We did not. Instead, multiple flat models were trained: in your case, it would be a separate model for PER and LOC entities and separate for CITY.

It is possible to use Flair to train the model closer to real nested one by introducing minor changes (adapting it to per-token multiclass classification)... using CRF layer in the mentioned setting however is not trivial and the overall performance without CRF would be worse by several F1 points.

Thus, when resources are not a problem, it is easier to use a less elegant way and treat nested named entity recognition as multiple flat named entity recognition problems.
